# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2024-04-03 07:47
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ladder', '0083_auto_20240403_0702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerreport',
            name='reason',
        ),
    ]
